<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; text-align: center; }
        .wrap { border: 5px solid #f59e0b; padding: 40px; margin: 40px; }
        .title { font-size: 36px; font-weight: bold; margin-bottom: 10px; }
        .subtitle { font-size: 20px; margin-bottom: 30px; }
        .name { font-size: 28px; font-weight: bold; margin: 10px 0; }
        .course { font-size: 22px; margin: 10px 0; }
        .footer { position: absolute; bottom: 40px; left: 0; right: 0; font-size: 12px; color: #666; }
    </style>
    <title>Sertifikat</title>
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self' data:; style-src 'unsafe-inline'">
    <meta name="referrer" content="no-referrer">
    <meta name="color-scheme" content="light dark">
    <meta name="x-robots-tag" content="noindex, nofollow">
    <meta name="generator" content="BelajarSiko">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class="wrap">
        <div class="title">Sertifikat Penyelesaian</div>
        <div class="subtitle">Diberikan kepada</div>
        <div class="name">{{ $user->name }}</div>
        <div class="subtitle">Telah menyelesaikan kelas</div>
        <div class="course">"{{ $course->title }}"</div>
        <div class="subtitle" style="margin-top:30px">Tanggal: {{ $certificate->generated_at->format('d M Y') }}</div>
        <div class="subtitle">Kode Unik: {{ $certificate->unique_code }}</div>
    </div>
    <div class="footer">BelajarSiko &mdash; Generated by system</div>
</body>
</html>
